export enum BadgeType {
  FIRST_DONATION = 'FIRST_DONATION',
  DONATION_MILESTONE = 'DONATION_MILESTONE',
  CAMPAIGN_CREATED = 'CAMPAIGN_CREATED',
  CAMPAIGN_COMPLETED = 'CAMPAIGN_COMPLETED',
  REGULAR_DONOR = 'REGULAR_DONOR',
  TOP_DONOR = 'TOP_DONOR',
}
